import 'package:flutter/material.dart';
import 'package:racfmn/helper/constant.dart';
import 'package:racfmn/helper/utility.dart';
import 'package:racfmn/ui/page/settings/widgets/headerWidget.dart';
import 'package:racfmn/ui/page/settings/widgets/settingsRowWidget.dart';
import 'package:racfmn/ui/theme/theme.dart';
import 'package:racfmn/widgets/custom_app_bar.dart';
import 'package:racfmn/widgets/custom_widgets.dart';

class TosPage extends StatelessWidget {
  const TosPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      
      appBar: AppBar(
        title: customTitleText(
          'Privacy and terms of service',
        ),
      ),
      body: ListView(
        physics: BouncingScrollPhysics(),
        padding: EdgeInsets.symmetric(horizontal: 20, vertical: 20),
        children: <Widget>[
          HeaderWidget(
            'Introduction',
          ),
          
          customText("Icademy which is under the umbrella of Lordsignet org. use and shield your individualized data that is provided or generated by us via connections to our cloud-based services", 
          style: TextStyle(fontSize: 15, height: 2)),
          SizedBox(height: 3),
          customText("Before going further and for the clarity of this privacy policy--'we', 'us' and 'our' refers to Icademy and 'you' refers to you--making use of the platform services", 
          style: TextStyle(fontSize: 15, height: 2)),
            SizedBox(height: 20),
         

            HeaderWidget('Terms of Services'),
                customText('''By signing up for Icademy, you accept our Privacy policy and agree NOT to:''', style: TextStyle(height: 2, fontSize: 15)),
                customText('''=>)  Use our service to send spam or scam users ''', style: TextStyle(height: 2, fontSize: 15)),
                customText('''=>) Use our service for Reverse Engineering''', style: TextStyle(height: 2, fontSize: 15)),
                customText('''=>) Reproduce the materials via any electronic,fax or others now known and yet to be invented''', style: TextStyle(height: 2, fontSize: 15)),
                 customText('''=>) Post Adult contents and its likes''', style: TextStyle(fontSize: 15)),
                  customText('''=>) Posting of links or casting aspersions or using uncouth language its completely prohibited in this platform''', style: TextStyle(height: 2, fontSize: 15)),
                   customText('''=>) We reserved the right to delete any third-party documents if the need arise.''', style: TextStyle(height: 2, fontSize: 15)),

                  SizedBox(height: 10),
                  customText('''We have limitless right to modify these Terms of Services at any time.'''),          
          
                HeaderWidget('Disclaimer'),
          customText('''=>) You are responsible for anything that happens to your gadgets when using services provided by this app.''',style: TextStyle(height: 2, fontSize: 15)),
          
           customText('''=>) Individuals are completely responsible for the posts/documents published using our publishing platform that works in tandem with this service''', style: TextStyle(height: 2, fontSize: 15)),
          
                 HeaderWidget('Legal'),
                  customText('''We do process your data on the ground that doing such will promote the interest of both parties--helps us to provide better services to you, to ward off fraudsters and its likes''', style: TextStyle(height: 2, fontSize: 15)),          
              
           
          
           
            SizedBox(height:30),          
         
        ],
      ),
    );
  }
}
